#!/usr/bin/env node
/**
 * harvest-todos.js
 * ----------------
 * Scans the repository for TODO / FIXME / HACK / XXX comments and
 * writes a structured markdown report to TODO_REPORT.md.
 *
 * Usage:  node scripts/harvest-todos.js
 *
 * Cross-platform: pure Node.js, no shell dependencies.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT        = path.resolve(__dirname, '..');
const OUTPUT_FILE = path.join(ROOT, 'TODO_REPORT.md');

const SKIP_DIRS = new Set([
  '.git','node_modules','venv','.venv','__pycache__','.ruff_cache',
  'htmlcov','coverage','dist','build','.pytest_cache','.kiro','output','logs',
  'pg_data','assets','.github',
]);

// Files that are excluded from scanning (self-referential false-positive sources)
const SKIP_FILES = new Set([
  'harvest-todos.js',
  'merge-report.js',
  'merge-quality.js',
  'TODO_REPORT.md',
  'MERGE_REPORT.md',
]);

const SEARCH_EXTS = new Set([
  '.ts','.tsx','.js','.jsx','.py','.md','.sh','.yml','.yaml',
]);

// Build the tag pattern from an array so the regex source itself never
// contains the literal annotation strings (avoids self-detection).
const TAGS = ['TODO', 'FIXME', 'HACK', 'XXX'];
const TAG_PATTERN = new RegExp('\\b(' + TAGS.join('|') + ')\\b[:\\s]*(.*?)$');

const byTag  = {};
TAGS.forEach(t => { byTag[t] = []; });
let total = 0;

function scanFile(filePath) {
  let src;
  try { src = fs.readFileSync(filePath, 'utf8'); } catch { return; }
  const lines = src.split('\n');
  const relPath = path.relative(ROOT, filePath).replace(/\\/g, '/');
  lines.forEach((line, idx) => {
    const m = TAG_PATTERN.exec(line);
    if (!m) return;
    const tag  = m[1];
    const text = m[2].trim().slice(0, 150);
    (byTag[tag] || (byTag[tag] = [])).push({ file: relPath, line: idx + 1, text });
    total++;
  });
}

function walkDir(dir, depth = 0) {
  if (depth > 8) return;
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
  for (const e of entries) {
    if (SKIP_DIRS.has(e.name)) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) { walkDir(full, depth + 1); continue; }
    if (SKIP_FILES.has(e.name)) continue;
    if (SEARCH_EXTS.has(path.extname(e.name))) scanFile(full);
  }
}

walkDir(ROOT);

const ts = new Date().toISOString().replace('T',' ').slice(0,19) + ' UTC';

const renderSection = (tag, items) => {
  if (!items || items.length === 0) return '';
  return '\n### ' + tag + ' (' + items.length + ')\n\n' +
    items.map(i => '- [`' + i.file + ':' + i.line + '`] ' + (i.text || '_(no message)_')).join('\n') + '\n';
};

const reportParts = [
  '# Annotation Harvest Report',
  '',
  '_Generated: ' + ts + ' · Total annotations: **' + total + '**_',
  '',
  '> Auto-generated by `scripts/harvest-todos.js`. Do not edit manually.',
  '',
];

TAGS.forEach(tag => {
  const section = renderSection(tag, byTag[tag]);
  if (section) reportParts.push(section);
});

fs.writeFileSync(OUTPUT_FILE, reportParts.join('\n').trim() + '\n');

const counts = TAGS.map(t => t + ': ' + (byTag[t] || []).length).join(', ');
console.log('[harvest-todos] Scanned repository');
console.log('[harvest-todos] Found ' + total + ' annotation(s) — ' + counts);
console.log('[harvest-todos] Report written to TODO_REPORT.md');
